### PR TITLE
[PPABV-42] fix: add missing search transaction test APIs to dev collection

### PR DESCRIPTION
**Pull request by dylantangredi-bvt**
#### List of Changes

- added search transaction by user email/fiscal code test APIs to dev collection
- renamed local and dev test APIs to match the existing ones from the UAT collection

#### Motivation and Context

- the APIs were missing from the dev collections but present in local and uat ones

#### How Has This Been Tested?

- tested with Postman

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by a-mannia — APPROVED** [review]

**Comment by infantesimone** [comment]
please check error in dev api test

**Comment by infantesimone** [comment]
please also add cases in which the search is unsuccessful, for example a user who has no transactions (404 or empty list) or an invalid input (and then test the 400)

**Review by infantesimone — CHANGES_REQUESTED** [review]
please add api test to test http error status

**Comment by infantesimone** [comment]
updated dev ecommerce-history db according to fiscal_code , test passed https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=181995&view=logs&j=118b0059-f864-5206-e77a-8084c09c6170&t=f12434d7-b992-5bc4-8c72-f73e2a335fee
/
/

**Comment by dylantangredi-bvt** [comment]
added requested change with [538484b](https://github.com/pagopa/pagopa-ecommerce-helpdesk-service/pull/145/commits/538484b4daf1f08d3292e882ab39ce4875afecdb)

**Comment by dylantangredi-bvt** [comment]
Sorry, the paths on dev collection were wrong, fixed with [05382b0](https://github.com/pagopa/pagopa-ecommerce-helpdesk-service/pull/145/commits/05382b095ee9fd762dd643aa005587c075996999)

> @dylantangredi-bvt please check api test fails https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=182962&view=logs&j=40c61e27-b082-57ff-0a81-36461d15544b&t=1d792f3f-fae2-5d33-af31-c9491906b03c
> 
> ```
> → Technical helpDesk SearchTransaction (v2) FISCAL_CODE 400 page over sized
>   POST https://api.dev.platform.pagopa.it/helpdesk/searchTransaction?pageNumber=0&pageSize=21 [404 Resource Not Found, 270B, 8ms]
>   1. Technical helpDesk SearchTransaction by FISCAL_CODE - Status code is 400 for request with page size over 20
> ```

**Review by infantesimone — APPROVED** [review]

**Review by infantesimone — APPROVED** [review]

**Pull request merged**
